[build]
command = "CI=false npm run build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[redirects]]
from = "/api/v1/*"
to = "http://api.ai-tutor.co.kr:8080/api/v1/:splat"
status = 200
