[build]
  # Next.js 프로젝트의 빌드 명령어와 출력 디렉토리 설정
  command = "npm run build && npm run export"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  
[[redirects]]
  # /api/v1/ 하위 경로의 모든 요청을 NGINX 서버로 프록시
  from = "/api/v1/*"
  to = "http://43.201.165.4:8080/api/v1/:splat"
  status = 200
  force = true

[[redirects]]
  # 그 외 모든 요청은 Next.js 앱으로 처리
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  # CORS 설정: 모든 요청에 대해 허용
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "*"

[functions]
  # Functions 디렉토리 설정 (필요한 경우만 사용)
  directory = "netlify/functions"
